### ISSUE TITLE
Unable to Inject scripts on remote web page

### ISSUE THREAD

**Issue by Rakesh15dec** [manifoldjs/ManifoldCordova#62] opened 2016-03-05 23:43 UTC
with Xcode 7 ,Cordova IOS 3.9.2 , IOS 9.2 , its keep giving error (white list rejection) on xcode console  even though manifest.json has entry under mjs_extended_scope for that domain ending with "_" and in config.xml domain has allow navigation plus access origin to "_" .  
even though xcode shows error page opens correctly in app.  only problem on that page no cordova plugin is accessible.

**Comment by boyofgreen** [comment] 2016-03-06 15:05
Can you share your manifest?  I'll take a look

**Comment by Rakesh15dec** [comment] 2016-03-06 19:36
I have attached , also putting entries here

{
  "name": "csv",
  "short_name": "csv",

  "start_url": "http://cacdtl02rr2340.itservices.com:8000/CSV_WL/apps/CSV/common/index.html",
  "mjs_cordova": {
     "plugin_mode": "client"
  },
  "mjs_import_scripts": [
    { "src": "js/index.js" }
  ],
  "mjs_api_access": [
    { "match": "http://cacdtl02rr2340.itservices.com:8000/CSV_WL/apps/CSV/common/*", "access": "cordova", "platform": "android,ios,windows" }

  ],

```
"mjs_extended_scope": ["http://cacdtl02rr2342.itservices.com:8000/CSV_WL/apps/CSV/common/*"],
```

   // without adding mjs_access_whitelist it was not working .
    "mjs_access_whitelist":[{"url":"http://cacdtl02rr2340.itservices.com:8000/*"}]

}
 if I don't add ms_access_whitelist it stops loading page with error white list rejection. I created the android app and it works absolutely fine in android , manifest is same in android except I did not need to add entry for ms_access_whitelist in android version

[manifest.txt](https://github.com/manifoldjs/ManifoldCordova/files/160522/manifest.txt)

**Comment by boyofgreen** [comment] 2016-03-07 16:49
mjs_extended_scope is designed to replace the more confusing mjs_access_whitelist.  To be clear you saying that the extended scope basically didn't work in your iOS project, but when you want back and added the access whitelist then it did?
  Also, it sounds like you are able to use the whitelist as a workaround until we get the fix deployed?

**Comment by Rakesh15dec** [comment] 2016-03-08 17:05
Yes thats correct  I am using whitelist as a workaround , I debug the code little and put some logging what I have seen cordova.js injected properly on web pages but hostedapp-bridge is failing. in logs it shows hostedapp-bridge.js injected but on browser it shows only cordova.js , hostedapp-bridge,js failed due to "chordova channel not triggered". I think thats why plugins are not loading..

second suggestion only : whitelist plugin allows "file://" URL but when using manifold plugin even in middle of transactions if I want to use "file://" url then i need to put that entry in mjs_access_whitelist otherwise manifold plugin gives white list rejection error. this case is with IOS only. in Ios code under scheme we should also include file.

**Comment by boyofgreen** [comment] 2016-03-10 16:55
Sorry about that.  We'll get fixed in the next release.  Also, thanks for the work around :)

**Comment by boyofgreen** [comment] 2016-04-22 18:20
looks like the issue is iOS only, and in this code chunk https://github.com/manifoldjs/ManifoldCordova/blob/2c42e4f9360cf6540a75897729645e238fcd4893/src/ios/CDVHostedWebApp.m#L513

**Closed as completed** 2017-01-30 22:28 UTC
